version: '3.1'

services:
  springapp:
    image: rahultechmumbai/javaspringapp:VERSION
    ports:
    - 8080:8080
    networks:
    - myoverlay
    environment:
    - MONGO_DB_HOSTNAME=mongodb
    - MONGO_DB_USERNAME=admin
    - MONGO_DB_PASSWORD=admin@123
    depends_on:
    - mongodb
    deploy:  # This will be considered only in docker swarm.
      replicas: 2
      update_config:
        parallelism: 1
        delay: 20s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        
  mongodb:
    image: mongo
    networks:
    - myoverlay
    environment:
    - MONGO_INITDB_ROOT_USERNAME=admin
    - MONGO_INITDB_ROOT_PASSWORD=admin@123
    volumes:
    - mongodb:/data/db    

volumes:
  mongodb:
    external: true # You have to manually create volume docker-compose will not create volume

networks:
  myoverlay:
    external: true # You have to manually create n/w docker-compose will not create n/w
      
